name: daily_pics
description: A new Flutter application.
version: 2.5.10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent: ^0.3.0
  cached_network_image: ^0.8.0
  connectivity: ^0.4.3+1
  event_bus: ^1.1.0
  flutter_staggered_grid_view: ^0.2.7
  image_picker: ^0.6.0+2
  json_annotation: ^2.0.0
  material_design_icons:
    git:
      url: https://github.com/Yaerin/flutter_packages.git
      path: material_design_icons
  package_info: ^0.4.0+3
  palette_generator: ^0.1.1
  photo_view: ^0.3.3
  scoped_model: ^1.0.1
  share: ^0.6.1+1
  shared_preferences: ^0.5.2
  url_launcher: ^5.0.2

dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - res/
