name: dailypics
description: A new Flutter application.
version: 2.1.7+200327

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_ionicons:
    git: https://github.com/KagurazakaHanabi/flutter_ionicons.git
  flutter_markdown:
    git: https://github.com/KagurazakaHanabi/flutter_markdown.git
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_staggered_grid_view: ^0.3.0
  image_picker: ^0.6.3+1
  json_annotation: ^3.0.1
  # package_info: ^0.4.0+13
  palette_generator: ^0.2.0
  path_provider: ^1.5.1
  photo_view: ^0.9.1
  qr: ^1.2.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.6
  # uni_links: ^0.2.0
  url_launcher: ^5.4.1

dev_dependencies:
  build_runner: ^1.7.4
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - res/
